revert(deps-dev): roll back flake8 version to v6
ExpediaGroup/expediagroup-python-sdk pull request #322
Opened 2024-02-06 14:44 UTC by OmarAlJarrah

* [X] Code is up-to-date with the `main` branch.
* [X] You've successfully built and run the tests locally.
* [] There are new or updated unit tests validating the change.

2024-02-06 17:12 UTC, mohnoor94 requested changes
Why?

2024-02-06 17:49 UTC, OmarAlJarrah commented
@mohnoor94 
> Why?
The version of `datamodel-code-generator` used by the `fastapi-code-generator` uses version `6.X.X` of `flake8`. Obviously `flake8` version `7.X.X` comes with a breaking change that breaks our SDK generator. As a conclusion, we are forced to stick with version `6.X.X` of `flake8` for the time being.

2024-02-07 08:49 UTC, osama-salman99 approved these changes

2024-02-07 12:34 UTC, mohnoor94 approved these changes

2024-02-07 12:36 UTC, merged